server:
  port: 80

spring:
  application:
    name: cloud-comsumer-service

eureka:
  client:
    register-with-eureka: true
    #是否从EurekaServer抓取自己的注册信息，默认为true，单节点无所谓，集群必须true才能让ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eurek,http://eureka7002.com:7002/eureka #集群版