server:
  port: 8001

spring:
  application:
    name: cloud-provider-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tiantian.springcloud.entities       #所有Entity别名类所在包
eureka:
  client:
    register-with-eureka: true
    #是否从EurekaServer抓取自己的注册信息，默认为true，单节点无所谓，集群必须true才能让ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eurek,http://eureka7002.com:7002/eureka #集群版
  instance:
      instance-id: payment8001 #访问路径可以显示ip
      prefer-ip-address: true #访问路径可以显示ip地址
      lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务端发送心跳的时间间隔，单位秒
      lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上限，单位秒（默认90），超时将剔除服务